### ISSUE TITLE
bounce with TransformView

### ISSUE THREAD

**Issue by X3gold** [CazzoPMX/KKPMX#13]
When I follow your instructions, it always destroys the facial morph for me.
With https://bowlroll.net/file/135250 and https://bowlroll.net/file/197410 I got the motion right.
But it would still be nice if you look over it again or did I just do something wrong?

**Comment by X3gold** [comment]
Got it working for me 0.00001 is displayed and I have confirmed it but it must be changed to 0.00000 then it also does not destroy the facial morphs would be good if you could write this in your instructions with pure.

**Comment by CazzoPMX** [comment]
Ok, I only know the solution because you mentioned where you come from, but the reason for that are your language Settings.

The issue at hand is that when applying the "Bounce", it will copy your Morphs, adjust them, and "paste" them back, but by doing so it converts the CSV from     [0 DOT 00]     into    [0 COMMA 00] which in effect breaks all decimal numbers into two integers after pasting them back. 

There is no workaround to this, you must configure your LanguageSettings to use Periods as Decimal Separator for it to work, or change to a SystemLocale which does it by default. I for example have a Japanese SystemLocale (the funny business with having Yen ¥ shown as Backslash \\ ) but my RegionLocale is set to my own Language -- Your UI Language as well as Date/Time display will refer to the latter, in case anyone worries.

https://support.microsoft.com/en-us/office/change-the-windows-regional-settings-to-modify-the-appearance-of-some-data-types-edf41006-f6e2-4360-bc1b-30e9e8a54989
-- Country = Japan
-- Local Region = <MyCountry>
-->> Additional Settings: Formats = <MyCountry>, Language for Non-Unicode Applications: Japanese
