### ISSUE TITLE
Crash All-in-one converter

### ISSUE THREAD

**Issue by X3gold** [CazzoPMX/KKPMX#16]
I discovered another bug, when the texture is in Japanese, the software crashes after the faces.

**Comment by CazzoPMX** [comment]
I had no time updating the Plugin in the past few months because of .... circumstances, but I encountered that bug at some point myself and it simply will not work when textures have CJK-Characters in their names. I added an fallback to replace them with escaped unicode versions, but then it cannot find the files..... 

As a workaround, you need to rename the files manually in the Explorer, PMX, and JSON file, for the time being.
Sorry for the inconvenience.

**Comment by X3gold** [comment]
Thanks for the answer, I did it the way you described it, fortunately it doesn't happen that often.
