### ISSUE TITLE
Isolate protruding surfaces wish function

### ISSUE THREAD

**Issue by X3gold** [CazzoPMX/KKPMX#4]
Hello, could you like KKBP (https://github.com/FlailingFog/KK-Blender-Porter-Pack/tree/V5-merger) in kkpmx_core under point 4 maybe add a function that this looks like here only as a morph and not cut out the graphics so that they remain untouched?
As an example only just as a morph:
**_Body_**
![cf_m_body_AlphaMask](https://user-images.githubusercontent.com/38250861/163438028-2ebb9108-a054-4e6f-8bd6-c7cab7edd830.png)
![Template Body 2048x2048 light](https://user-images.githubusercontent.com/38250861/163438040-20a98917-7d6e-4142-b7b4-c765660d6d28.png)
**_Bra_**
![cf_m_bra_05 -460990_AlphaMask](https://user-images.githubusercontent.com/38250861/163438422-78ff1416-85a7-4614-838f-79e9daf2f6f4.png)
![Template cf_m_bra_05 -460990 1024x512 light](https://user-images.githubusercontent.com/38250861/163438437-92168e63-c0a5-4cb4-815e-cb7386c1e109.png)
**_Inner_**
![cf_m_top_inner01 -456512_AlphaMask](https://user-images.githubusercontent.com/38250861/163438458-3c4a419e-7202-49af-b39f-e9623c82b69b.png)
![Template cf_m_top_inner01 -456512 1024x1024 light](https://user-images.githubusercontent.com/38250861/163438465-92d0838a-c8ec-413e-9306-37c08a45eb50.png)

The AlphaMask so everything green and black should then be invisible so morph.

**Comment by X3gold** [comment]
Do you mean here under point 0

Choose:
-- [0] Use best-guess defaults from KK :: this will ask for 2-3 idx/names and perform 1-2 runs
-- [1] Input manual bounding box (and cut out completely into new material) :: 1 material, 0 runs
-- [2] Input manual bounding box (and scan against the base material)       :: 2 materials, 1 run
-- [3] Full scan (Warning: this WILL take long depending on material size)  :: 2 materials, 1 run

And then under 1 or 2?

-- KK Defaults: Restrict to optimized box around chest ?:
0: Detailed
1: Rough Box (small)
2: Rough Box (big)
3: No

This figure looks like this in PMX Editor
![『32』凜子姉V06](https://user-images.githubusercontent.com/38250861/166001704-95b6702d-d392-4f9c-b3ed-995753bb74c9.png)

0: Detailed
![29-04-2022_20-30-15](https://user-images.githubusercontent.com/38250861/166003832-7cc69969-64e2-4a63-82a1-f4dccaefa56c.jpg)

1: Rough Box (small)
![29-04-2022_20-34-04](https://user-images.githubusercontent.com/38250861/166004809-f02ecf3a-aace-456e-9151-c2d4d2fd7f7d.jpg)

2: Rough Box (big)
![29-04-2022_20-35-52](https://user-images.githubusercontent.com/38250861/166005423-07c1e0c7-173f-4430-b2f5-4086ef2ded10.jpg)
![29-04-2022_20-45-06](https://user-images.githubusercontent.com/38250861/166007170-ddcae92f-7dff-4627-8184-f1a3230e92b5.jpg)

3: No
![29-04-2022_21-08-05](https://user-images.githubusercontent.com/38250861/166011050-5b8dca21-45b0-49b9-8b8f-5533ae223bdf.jpg)
![29-04-2022_21-08-55](https://user-images.githubusercontent.com/38250861/166012968-eb91e29b-2c3b-4121-affd-8cde0317d54b.jpg)

And here still that with all inner always comes through
![29-04-2022_21-10-04](https://user-images.githubusercontent.com/38250861/166022870-e2f40c3e-17a0-46ee-88fb-3ea73930ff09.jpg)

**Comment by CazzoPMX** [comment]
Well, I think I might look into the idea regardless, but for these kind of things theres's the manual bounding box, I guess.

**Comment by X3gold** [comment]
Thanks for this tip, it worked

**Comment by X3gold** [comment]
Hello, can you help me maybe one how I use the Manuel, because have no idea at all in this area I am a total beginner

**Comment by CazzoPMX** [comment]
Sure! 

For each of the 3 axis, you want to find the minimum and maximum (basically the width, height, and depth of your bounding box).

You need to toggle the Vertex Selection as well as the Selection Guide (F7 or the [G] Button in the toolbar) for that. I would also advise to click the "Front" Button at the bottom which hides all non-visible vertices and turn off the Handles (the redbluegreen thingy at the top right).

All directions are based on the character looking away from you (Red=X Axis Left, Blue=Z Axis Forward, Green=Y Axis Upwards)

To determine lets say the X Axis (right arm > left arm) and assuming we want to include the full width of the torso:
1. So from the center, roughly select the outer most right vertices of the torso. (Hard to describe, but you'd get a feeling for what you want when you did it a couple of times)
2. In the Selection Guide, click on [Get OBJ]. The Box below should be filled with the vertices you selected
3. Each Row is read as "Index (X, Y, Z)", and since we want the minimum, find the smallest number of 'X' and write it down.
4. Now repeat Step 1-3 for the left side, but write down the biggest X-Value.

For the Green Y-Axis, you would repeat that but choose the minimum and maximum height that you want to include in the box
For the Blue Z-Axis, the front is actually the minimum, and the back points towards the maximum. You can also just chose an arbitary low / high number (like -5 & +5 for Z) if you want to include everything.

For the actual input in the Program, you can choose between A) manually inputing them as the command requests or B) entering them as [ -X, -Y, -Z ] on the first and [ X, Y, Z] on the second request to speed it up.
If this sounds confusing, do the first variant, and the Programm will generate the correct [] List for you into the #editLog, from where it can be copied to repeat the result if needed.

**Comment by X3gold** [comment]
Thank you, worked very well.

Could you help me with this figure?
![84021549_p5](https://user-images.githubusercontent.com/38250861/167859478-5bb77080-5f57-4698-a017-81ae01d118ac.png)

I still get the image under Manuel or Automatic but under 2: Rough Box (big) and 3: No, the image is gone but the neck is partially missing.
![11-05-2022_15-22-17](https://user-images.githubusercontent.com/38250861/167860376-0d0bdc1b-f901-4165-9a6b-19619b7d0093.jpg)
![11-05-2022_15-23-08](https://user-images.githubusercontent.com/38250861/167860396-4172e00b-e69b-4019-8468-4faaa0488812.jpg)

**Comment by X3gold** [comment]
The with the chest has settled had to take the whole simply about manual 1.

**Comment by chamo37** [comment]
The button doesn't appear in the upper left.

The dll is in plugins.

In which file should I put KKPMX-master in the first place?

I tried putting it in BepInEx, plugins and KK_Plugins, but it didn't make any sense.
