### ISSUE TITLE
Part of the hair falls to the floor

### ISSUE THREAD

**Issue by X3gold** [CazzoPMX/KKPMX#5]
For these girls, after item 5: All-in-one converter or item 12: Run Rigging Helpers, some of the hair falls to the floor.

https://drive.google.com/file/d/14I8rLnlJyQA1R5RE0jFACDzZ_Oh4s9lo/view?usp=sharing

Here is an example:
![ezgif-2-e8c81edbec](https://user-images.githubusercontent.com/38250861/164896167-e6a8222a-4bbc-469f-987d-31cb18524c63.gif)

**Comment by CazzoPMX** [comment]
I'll look into it the next days

**Comment by CazzoPMX** [comment]
Just a reminder, I cannot add all assets in existence since I don't (and won't) go through them all, so I add these things as they come up as issue or otherwise.

I added her rigging as pattern, but one or two Rigids have to be fixed to [Bone Track] manually as usual.
Will be in the next version.

The backhair has no unique identification on which I could anchor a pattern, so you would have to run that through [12: Rigging] with option 2 and input the chain of bones to rig manually.

**Comment by X3gold** [comment]
Ok thanks
